SystemOrganization addCategory: #JupyterTalk!
SystemOrganization addCategory: 'JupyterTalk-Core'!
SystemOrganization addCategory: 'JupyterTalk-Display'!
SystemOrganization addCategory: 'JupyterTalk-Messages-Comm'!
SystemOrganization addCategory: 'JupyterTalk-Messages-IOPub'!
SystemOrganization addCategory: 'JupyterTalk-Messages-Shell'!
SystemOrganization addCategory: 'JupyterTalk-Widgets-experimental'!
