#!/bin/bash
script_home=$(dirname $0)
script_home=$(cd $script_home && pwd)
# requirements ....
# sudo apt-get install unzip 
#64 bits version
wget -q -O tmp.zip https://get.pharo.org/64/80+vm  && unzip tmp.zip && rm tmp.zip
#curl -L https://get.pharo.org/64/80+vm | bash
$script_home/pharo $script_home/Pharo.image eval --save "Metacello new baseline: 'JupyterTalk';repository: 'github://jmari/JupyterTalk:master/repository';load:'all'" 
