#!/bin/bash
script_home=$(dirname $0)
script_home=$(cd $script_home && pwd)
# requirements ....
# sudo apt-get install unzip 
#64 bits version
#curl -L https://get.pharo.org/64/80+vm | bash
pwd
ls -all 
/home/jovyan/pharo-vm/lib/pharo/5.0-202002121043/pharo /home/jovyan/Pharo.image eval "365 * 10"
