#!/bin/bash
script_home=$(dirname $0)
script_home=$(cd $script_home && pwd)
# requirements ....
# sudo apt-get install unzip 
#64 bits version
curl -L https://get.pharo.org/64/80+vm | bash

./pharo ./Pharo.image eval --save "Metacello new baseline: 'JupyterTalk';repository: 'github://jmari/JupyterTalk:master/repository';load:'all'" 
